export const textLockCopy = {
  actions: {
    continueRun: "Continue saved run",
    continueToNextChest: "Continue to next chest",
    moveLeft: "Move left",
    moveRight: "Move right",
    newRun: "Start new test run",
    reset: "Reset current lock",
    selectNextPin: "Select next pin",
    selectPreviousPin: "Select previous pin",
    selectPin: "Select pin",
  },
  labels: {
    chest: "Chest",
    debugUi: "Debug UI",
    eventLog: "Event log",
    invalidMoves: "Invalid moves",
    invalidMoveEvent: "invalid move",
    ignoredEvent: "ignored",
    keyboardHelp: "Keyboard help",
    keyboardMoveLeft: "`A` or `ArrowLeft` moves the selected pin left",
    keyboardMoveRight: "`D` or `ArrowRight` moves the selected pin right",
    keyboardReset: "`R` resets the current lock",
    keyboardSelectPreviousPin: "`W` or `ArrowUp` selects the previous pin",
    keyboardSelectNextPin: "`S` or `ArrowDown` selects the next pin",
    keyboardSelectPin: "`1-9` select a pin by index",
    left: "left",
    lockpickBrokeEvent: "lockpick broke after invalid move",
    lockpicks: "Lockpicks",
    maxInvalidMoves: "Max invalid moves per pick",
    moveHint: "Pick a pin and move it directly",
    moveHorizontal: "Move left/right",
    moveVertical: "Move up/down",
    movedEvent: "moved",
    next: "Next",
    noValue: "Not started",
    onTarget: "on target",
    oreUnit: "ore",
    openedChestEvent: "opened chest",
    oreNuggets: "Ore nuggets",
    pin: "Pin",
    pinColumns: "Pin columns",
    pinControls: "Pin controls",
    pinPrefix: "pin",
    position: "Position",
    range: "Range",
    resetChestEvent: "reset chest",
    reset: "Reset",
    rewardLockpicks: "lockpicks",
    rewardSummary: "Latest chest reward",
    right: "right",
    rules: "Rules",
    selectedPin: "Selected pin",
    selectedPinEvent: "selected pin",
    selectedPinFromKeyboardEvent: "selected pin from keyboard",
    solvedChestEvent: "solved chest",
    solverHint: "Solver path length",
    startedChestEvent: "started chest",
    state: "State",
    target: "Target",
    toInitialState: "to initial lock state",
    continuedSavedChestEvent: "continued saved chest",
  },
  messages: {
    active:
      "Use the text controls to inspect dependencies, verify valid moves, and reproduce invalid move damage.",
    failed:
      "Run failed. No lockpicks remain, so lock interaction is blocked until a new run starts.",
    idle: "Start a run to inspect the generated lock and test move behavior.",
    invalid:
      "Invalid moves leave every pin in place and only damage the current lockpick.",
    noEvents: "No gameplay events yet.",
    saved: "A previously saved run is available from the last opened chest.",
    solved:
      "Lock solved. Advance to the next chest to generate a harder test lock and save the run.",
  },
  states: {
    active: "Active",
    failed: "Failed",
    solved: "Solved",
  },
  subtitle:
    "Text-first browser harness for validating lock generation, move rules, invalid move damage, and manual reset behavior.",
  title: "Wedge's Trial Lock Harness",
} as const;
